version: '3.9'

services:
  api-users:
    container_name: tracing-api-users
    build: ./src/Services/Users.Api
    ports:
      - "8010:80"
      - "8011:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - otel-collector
      - db-sqlserver

  api-orders:
    container_name: tracing-api-orders
    build: ./src/Services/Orders.Api
    ports:
      - "8020:80"
      - "8021:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - otel-collector
      - db-sqlserver

  api-inventory:
    container_name: tracing-api-inventory
    build: ./src/Services/Inventory.Api
    ports:
      - "8030:80"
      - "8031:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - otel-collector

  active-mq:
    container_name: tracing-active-mq
    image: "rmohr/activemq:latest"
    ports:
      - 61616:61616 # JMS
      - 5672:5672   # AMQP
      - 8161:8161   # UI

  db-sqlserver:
    container_name: tracing-db-sqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1440:1433"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rD"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  otel-collector:
    container_name: tracing-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - prometheus

  jaeger:
    container_name: tracing-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"

  zipkin:
    container_name: tracing-zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    container_name: tracing-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml  # the config file in container must have the file extension ".yml"
    ports:
      - "9090:9090"
