version: '3.9'

services:
  api-users:
    container_name: tracing-api-users
    build: ./src/Services/Users.API
    ports:
      - "8001:80"
    depends_on:
      - otel-collector
      - db-sqlserver

  db-sqlserver:
    container_name: tracing-db-sqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1440:1433"
    environment:
      MSSQL_SA_PASSWORD: "P@ssw0rD"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  otel-collector:
    container_name: tracing-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - prometheus

  jaeger:
    container_name: tracing-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin:
    container_name: tracing-zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    container_name: tracing-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml  # the config file in container must have the file extension ".yml"
    ports:
      - "9090:9090"
