# configure receivers
# for more receiver values see:
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
receivers:
  otlp:
    protocols:
      http:
      grpc:

# configure exporters
exporters:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
    format: proto
  prometheus:
    endpoint: :9090
    #const_labels:
    #  label1: value1
  logging:
    loglevel: debug

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, zipkin, logging]