// <auto-generated />
using DistributedTracingDotNet.Services.Users.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributedTracingDotNet.Services.Users.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221004223435_AddInitialUserDbSeedData")]
    partial class AddInitialUserDbSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DistributedTracingDotNet.Services.Users.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Khadeeja",
                            LastName = "Glenn"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Monty",
                            LastName = "Vang"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Roseanne",
                            LastName = "Hodges"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Antoine",
                            LastName = "Bellamy"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Felicia",
                            LastName = "Dowling"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Sidrah",
                            LastName = "Humphries"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Carly",
                            LastName = "Haas"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Isadora",
                            LastName = "Greig"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Cadi",
                            LastName = "Bull"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jaxon",
                            LastName = "Gentry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
